// <auto-generated />
using System;
using FriendwithBooksBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FriendwithBooksBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250524140423_AddFlashSale")]
    partial class AddFlashSale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FriendwithBooksBackend.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<int>("AvgRating")
                        .HasColumnType("integer")
                        .HasColumnName("avgrating");

                    b.Property<string>("Binding")
                        .HasColumnType("text")
                        .HasColumnName("binding");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImgURL")
                        .HasColumnType("text")
                        .HasColumnName("imgurl");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("PageNum")
                        .HasColumnType("text")
                        .HasColumnName("pagenum");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTime>("PublishYear")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publishyear");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.Property<string>("Supplier")
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TotalRating")
                        .HasColumnType("integer")
                        .HasColumnName("totalrating");

                    b.HasKey("BookID");

                    b.HasIndex("CategoryID");

                    b.ToTable("books");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Cart", b =>
                {
                    b.Property<int>("CartID")
                        .HasColumnType("integer")
                        .HasColumnName("cartid");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int>("BookID")
                        .HasColumnType("integer")
                        .HasColumnName("bookid");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdate");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("CartID", "UserID", "BookID");

                    b.HasIndex("BookID");

                    b.HasIndex("UserID");

                    b.ToTable("carts");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("categoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("text")
                        .HasColumnName("categoryname");

                    b.Property<int?>("ParentID")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.HasKey("CategoryID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.FlashSale", b =>
                {
                    b.Property<int>("FlashSaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("flashsaleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlashSaleID"));

                    b.Property<int>("BookID")
                        .HasColumnType("integer")
                        .HasColumnName("bookid");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discountpercent");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endtime");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starttime");

                    b.HasKey("FlashSaleID");

                    b.HasIndex("BookID");

                    b.ToTable("flashsales");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("orderdate");

                    b.Property<int>("PaymentMethodID")
                        .HasColumnType("integer")
                        .HasColumnName("paymentmethodid");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("totalamount");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("OrderID");

                    b.HasIndex("PaymentMethodID");

                    b.HasIndex("UserID");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .HasColumnType("integer")
                        .HasColumnName("orderdetailid");

                    b.Property<int>("OrderID")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<int>("BookID")
                        .HasColumnType("integer")
                        .HasColumnName("bookid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unitprice");

                    b.HasKey("OrderDetailID", "OrderID", "BookID");

                    b.HasIndex("BookID");

                    b.HasIndex("OrderID");

                    b.ToTable("orderdetails");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paymentmethodid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentMethodID"));

                    b.Property<string>("MethodName")
                        .HasColumnType("text")
                        .HasColumnName("methodname");

                    b.HasKey("PaymentMethodID");

                    b.ToTable("paymentmethods");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .HasColumnType("integer")
                        .HasColumnName("reviewid");

                    b.Property<int>("BookID")
                        .HasColumnType("integer")
                        .HasColumnName("bookid");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewdate");

                    b.HasKey("ReviewID", "BookID", "UserID");

                    b.HasIndex("BookID");

                    b.HasIndex("UserID");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transactionid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("integer")
                        .HasColumnName("orderid");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paymentdate");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text")
                        .HasColumnName("paymentstatus");

                    b.HasKey("TransactionID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrationdate");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("UserID");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Book", b =>
                {
                    b.HasOne("FriendwithBooksBackend.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Cart", b =>
                {
                    b.HasOne("FriendwithBooksBackend.Models.Book", "Book")
                        .WithMany("Carts")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendwithBooksBackend.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.FlashSale", b =>
                {
                    b.HasOne("FriendwithBooksBackend.Models.Book", "Book")
                        .WithMany("FlashSales")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Order", b =>
                {
                    b.HasOne("FriendwithBooksBackend.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendwithBooksBackend.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.OrderDetail", b =>
                {
                    b.HasOne("FriendwithBooksBackend.Models.Book", "Book")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendwithBooksBackend.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Review", b =>
                {
                    b.HasOne("FriendwithBooksBackend.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendwithBooksBackend.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Transaction", b =>
                {
                    b.HasOne("FriendwithBooksBackend.Models.Order", "Order")
                        .WithOne("Transaction")
                        .HasForeignKey("FriendwithBooksBackend.Models.Transaction", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Book", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("FlashSales");

                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FriendwithBooksBackend.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
